* fixed trace feature. * added udev rule to start awds
git-svn-id: svn+ssh://svn.berlios.de/svnroot/repos/awds/routing@93 d2c7b242-0724-0410-acbd-db3348fdb001

diff --git a/debian/awds.init b/debian/awds.init
--- a/debian/awds.init
+++ b/debian/awds.init
@@ -23,6 +23,8 @@ PIDFILE=/var/run/awds.pid
 SCRIPTNAME=/etc/init.d/$NAME
 CONFFILE=/etc/awds.conf
 
+/bin/touch /tmp/aa
+
 # Exit if the package is not installed
 [ -x "$DAEMON" ] || exit 0
 
@@ -76,6 +78,24 @@ do_stop()
 }
 
 
+do_hotplug() 
+{
+
+    echo "$ACTION-$SUBSYSTEM-$INTERFACE" vs "add-net-$NET_DEV"> /tmp/xxx-$$
+    [ "$START_BY_UDEV" == yes ] || return 0
+
+    if [ "$ACTION-$SUBSYSTEM-$INTERFACE" = "add-net-$NET_DEV" ]; then
+	echo Jo > /tmp/jo.txt
+	do_start    
+    fi
+
+    if [ "$ACTION-$SUBSYSTEM-$INTERFACE" = "remove-net-$NET_DEV" ]; then
+	do_stop
+    fi
+
+}
+
+
 case "$1" in
     start)
 
@@ -99,23 +119,27 @@ case "$1" in
 	2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
     esac
     ;;
+    hotplug)
+	do_hotplug > /dev/null
+	touch /tmp/fnord	
+    ;;
     reload|restart|force-reload)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
 	#
-    log_daemon_msg "Restarting $DESC" "$NAME"
-    do_stop
-    case "$?" in
-	0|1)
-	do_start
+        log_daemon_msg "Restarting $DESC" "$NAME"
+	do_stop
 	case "$?" in
-	    0) log_end_msg 0 ;;
-	    1) log_end_msg 1 ;; # Old process is still running
-	    *) log_end_msg 1 ;; # Failed to start
+		0|1)
+	    do_start
+	    case "$?" in
+		0) log_end_msg 0 ;;
+		1) log_end_msg 1 ;; # Old process is still running
+		*) log_end_msg 1 ;; # Failed to start
 	esac
 	;;
-	*)
+    *)
 	  	# Failed to stop
 	log_end_msg 1
 	;;
